Repository Ankit-raj-11/T-race, pull requests merged in 2025-10, with the labels that each got.

#49 Fix timer and input autofocus issues
  src/components/Timer.js
  src/pages/race.js
Labels: bug, hacktoberfest2025, feature

#50 Improve Firebase Security by Using .env and Adding .env.example
  src/context/AuthContext.js
  src/firebase.js
Labels: bug, hacktoberfest2025

#52 add userscore schema
  src/models/UserScore.js
Labels: hacktoberfest2025, backend

#68 Inserted a logo in header component
  src/components/T-Race.png
Labels: enhancement, good first issue, hacktoberfest2025, hacktoberfest-accepted, feature

#67 feat:Added link to Practice Mode from home page
  src/pages/index.js
Labels: good first issue, hacktoberfest2025

#69 fix: save race statistics to database
  .editorconfig
  .prettierrc.js
  src/pages/race.js
Labels: hacktoberfest2025, backend
